spring:
  cloud:
    stream:
      codec:
        avro:
          readerSchema: "io.igx.android.Sensor"
      bindings:
        input:
         destination: sensor-topic
confluent:
  schemaregistry:
    endpoint: http://192.168.99.100:8081
server:
  port: 0