fixedDelay: 1


spring:
  cloud:
    stream:
      bindings:
        output:
          destination: sensor-topic
          contentType: "avro/binary"
#confluent:
#  schemaregistry:
#    endpoint: http://192.168.99.100:8081
  rabbitmq:
    host: localhost
    port: 16001


server:
  port: 0
